version: "3.8"

services:
  backend:
    build:
      args:
        - NODE_ENV=development
        # - PORT=5001
      context: backend
      target: development
    command: npm run start-watch
    environment:
      - DATABASE_DB=root
      - DATABASE_USER=root
      - DATABASE_PASSWORD=secret
      - DATABASE_HOST=db
      - NODE_ENV=development
      - JWT_SECRET=secret
      - DATABASE_PORT=5432
      # - PORT=5001
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    ports:
      - 80:80
      - 9229:9229
      - 9230:9230
    volumes:
      - ./backend/src:/code/src:ro
      - ./backend/package.json:/code/package.json
      - ./backend/package-lock.json:/code/package-lock.json
      - back-notused:/opt/app/node_modules
    networks:
      - public
      - private
    depends_on:
      - db
  db:
    # Using postgres
    container_name: db-postgres
    ports:
      - 5433:5432
    hostname: db
    # 127.0.0.1
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    image: postgres:latest
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    networks:
      - public
      - private

  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src
      - /code/node_modules
    networks:
      - public
    depends_on:
      - backend
networks:
  public:
  private:
volumes:
  back-notused:
  db-data:
