services:
  postgres:
    container_name: postgres
    ports:
      - 5433:5432
    hostname: 127.0.0.1
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    image: postgres:latest
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
